package de.uulm.einhoernchen.flashcardsapp.Const;

/**
 * @author Jonas Kraus jonas.kraus@uni-ulm.de
 * @since 2016.08.22
 */
public enum Constants {
    ROOT_LIST, CATEGORY_LIST, CARD_DECK_LIST, FLASH_CARD_LIST, FLASH_CARD_DETAIL, PLAY, FLASH_CARD_CREATE,
    PLAY_ANSWER, PLAY_QUESTION,
    SETTINGS_LEARN_MODE_KNOWLEDGE, SETTINGS_LEARN_MODE_DATE, SETTINGS_LEARN_MODE_RANDOM, SETTINGS_LEARN_MODE_DRAWER
}
